config/routes.rb
Kibble::Application.routes.draw do
  
  get 'sign/index'
  root to: 'home#index'
  
  resources :sign
  resources :users
  resources :cases, only: [:new, :create, :index, :show]
  resources :sessions, only: [:new, :create, :destroy]
  
  #get "users/family_settings"
  
  match '/signup',  to: 'users#new',            via: 'get'
  match '/signin',  to: 'sessions#new',         via: 'get'
  match '/signout', to: 'sessions#destroy',     via: 'delete'
  
end

app/views/layouts/_footer.html.erb
		<!-- Footer -->
    <div class="container">
      <hr>
      <footer>
        <p>&copy; Grand Rounds Health 2013</p>
				<p><a href="#">www.grandroundshealth.com</a></p>
				<ul class="list-unstyled small">
					<li><a href="#">Blog</a></li>
					<li><a href="#">Our Specialists</a></li>
				</ul>
				<ul class="list-unstyled small">
					<li><a href="#">Terms of Service</a></li>
					<li><a href="#">Privacy Policy</a></li>
				</ul>
      </footer>
    </div> <!-- /footer -->

app/views/layouts/_messages.html.erb
<%# Rails flash messages styled for Bootstrap 3.0 %>
<% flash.each do |name, msg| %>
  <% if msg.is_a?(String) %>
	<!-- default flash message -->
	<script>
	Messenger.options = {
	    extraClasses: 'messenger-fixed messenger-on-top messenger-on-left',
	    theme: 'flat',
	}
	
	Messenger().post({
	  message: '<%= content_tag :div, msg, :id => "flash_#{name}" %>',
		type: "success",
	  hideAfter: 3,
	  hideOnNavigate: true
	});

	
	</script>
	
    <!-- ><div class="alert center-block alert-flash alert-<%= name.to_s == 'notice' ? 'success' : 'danger' %>" id="alert">
    <button type="button" class="close" data-dismiss="alert" aria-hidden="true">&times;</button>
     <%= content_tag :div, msg, :id => "flash_#{name}" %>
    </div> -->
  <% end %>
<% end %>

app/views/layouts/_navbar.html.erb
<%# navbar styled for Bootstrap 3.0 %>
	 <div class="navbar navbar-grnds navbar-fixed-top">
      <div class="container">
        <div class="navbar-header">
          <button type="button" class="navbar-toggle" data-toggle="collapse" data-target=".navbar-collapse">
            <span class="icon-bar"></span>
            <span class="icon-bar"></span>
            <span class="icon-bar"></span>
          </button>
					<span class="navbar-brand"><%= link_to(image_tag("grlogo-white.png"), { :controller => "home", :action => "index"}) %></span>
        </div>
        <div class="navbar-collapse collapse">
					<ul class="nav navbar-nav navbar-right">
						<% if false %>
						<% if current_user.jamba == true %><li><%= image_tag "logo-jambajuice.png", :class => "cobrand" %></li><% else %> hi <% end %>
						<% end %>
				      <li class="dropdown active">
								<% if signed_in? %>
					      <li class="dropdown active">
					        <%= link_to current_user.firstname + " " + current_user.lastname, "#", :class =>"dropdown-toggle", "data-toggle" => "dropdown" %>
					        <ul class="dropdown-menu">
										<li><%= link_to 'Homepage', current_user %></li>
										<li class="divider"></li>
										<li><a href="#">Case: Deep Vein Trombones</a></li>
										<li><a href="#">Case: Acute Rectal-Crainial Translocation</a></li>
										<li class="divider"></li>
					          <li><a href="#">Start a New Visit</a></li>
					          <li><a href="#">Start a New Opinion</a></li>
					          <li class="divider"></li>
										<li><%= link_to 'Account Settings', edit_user_path(current_user) %></li>
					          <li><%= link_to "Sign out", signout_path, method: "delete" %></li>
					        </ul>
					      </li>
			          <% else %>
			            <%= link_to "Sign in", signin_path, :class => "dropdown-toggle" %>
			          <% end %>
				      </li>
				    </ul>
        </div><!--/.navbar-collapse -->
      </div>
    </div>

app/views/layouts/_navigation.html.erb
<%# navigation styled for Bootstrap 3.0 %>
<nav class="navbar navbar-inverse navbar-fixed-top">
  <div class="container">
    <div class="navbar-header">
      <button type="button" class="navbar-toggle" data-toggle="collapse" data-target=".navbar-collapse">
        <span class="sr-only">Toggle navigation</span>
        <span class="icon-bar"></span>
        <span class="icon-bar"></span>
        <span class="icon-bar"></span>
      </button>
      <%= link_to 'Home', root_path, class: 'navbar-brand' %>
    </div>
    <div class="collapse navbar-collapse">
      <ul class="nav navbar-nav">
        <%= render 'layouts/navigation_links' %>
      </ul>
    </div>
  </div>
</nav>

app/views/layouts/_navigation_links.html.erb
<%# add navigation links to this file %>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title><%= content_for?(:title) ? yield(:title) : "kibble" %></title>
    <meta name="description" content="<%= content_for?(:description) ? yield(:description) : "Myapp" %>">
    <%= stylesheet_link_tag "application", media: "all", "data-turbolinks-track" => true %>
    <%= javascript_include_tag "application", "data-turbolinks-track" => true %>
    <%= csrf_meta_tags %>
		<%= yield :script %>
		<script src="//code.jquery.com/ui/1.10.4/jquery-ui.js"></script>
	  <link rel="stylesheet" href="//code.jquery.com/ui/1.10.4/themes/flick/jquery-ui.css">
		<link href="//netdna.bootstrapcdn.com/font-awesome/4.0.3/css/font-awesome.css" rel="stylesheet">
		
  </head>
  <body>
     <%= render 'layouts/messages' %>
		<header>
			<%= render 'layouts/navbar' %>
		</header>
    <main role="main">
       <%= yield %>
    </main>
		<footer>
			<%= render 'layouts/footer' %>
		</footer>
  </body>
</html>